name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar las credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # 4. Inicializar Terraform
      - name: Terraform Init
        run: cd terraform && terraform init

      # 5. Aplicar Terraform
      - name: Terraform Apply
        run: cd terraform && terraform apply -auto-approve

      # 6. Instalar dependencias del proyecto Serverless
      - name: Install dependencies
        run: cd serverless && npm install

      # 7. Desplegar con Serverless
      - name: Deploy Serverless
        run: cd serverless && npx serverless deploy --stage prod
